config/routes.rb
Rails.application.routes.draw do

  resources :gams_paths
  resources :event_job_job_associations
  resources :event_job_period_associations
  resources :periods
  resources :jobs
  resources :events
  resources :users
  resources :microposts,          only: [:create, :destroy]

  root 'static_pages#home'

  get 'sessions/new'
  get 'users/new'
  get 'signup'     => 'users#new'
  get 'login'      => 'sessions#new'
  get 'home'        => 'static_pages#home'
  get 'impression' => 'static_pages#impression'
  get 'offer'      => 'static_pages#offer'
  get 'tcpsp'      => 'static_pages#tcpsp'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'impressum'    => 'static_pages#impressum'

  post 'event_job_periods/delete_old_plan', :to => 'event_job_period_associations#delete_old_plan'
  post 'event_job_periods/optimize', :to => 'event_job_period_associations#optimize'
  post 'event_job_periods/read_optimization_results', :to => 'event_job_period_associations#read_optimization_results'
  post "periods/change", as: :change_periods
  post   'login'   => 'sessions#create'
  post   'logout'   => 'sessions#destroy'

  delete 'logout'  => 'sessions#destroy'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def impression
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
    @microposts = Micropost.all
  end

  def offer
  end

  def about
  end

  def contact
  end

  def impressum
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "Über uns") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | EvenTraum</title>
</head>
<body>
<h1>Über die Gründer</h1>
<br>
<div style="text-align:right">
  <div class="image">
    <div style=><%=image_tag("Xelat.jpg", width: "140", height: "200")%></div>
    <p> Xelat Akcam</p>
  </div>

  <div class="image">
    <div style=><%=image_tag("Hayat.jpg", width: "140", height: "200")%></div>
    <p> Hayat Boulakhrif </p>
  </div>

  <div class="image">
    <div style=><%=image_tag("Nadia.jpg", width: "150", height: "200")%></div>
    <p> Nadia Kruszewski </p>
  </div>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<p>Die drei Gründerinnen der Event-Agentur EvenTraum sind Master-Studentinnen der Wirtschaftswissenschaft im Major Operations Management and Research an der Gottfried Wilhelm Leibniz Universität. Die drei Damen kennen sich bereits aus dem vorangegangenen Studium, den sie erfolgreich mit dem Titel Bachelor of Science abgeschlossen haben.
</p>
<br>
<h1>Über das Unternehmen</h1>
<p>Im Rahmen der Veranstaltung „Entwicklung von Anwendungssystemen“
  am <a href="http://www.prod.uni-hannover.de">Institut für Produktionswirtschaft</a> bei Prof. Dr. Helber ist die Web-Applikation „EvenTraum“ entwickelt worden.<br>
  Die Event-Agentur EvenTraum beschäftigt sich mit der Planung verschiedener Events mit unterschiedlichen Abläufen und Veranstaltungsterminen. Die Web-Applikation dient der Visualisierung der Ergebnisse eines sogenannten Multi-Projekt-Planungsproblems unter zeitlichen Restriktionen, welches mit Hilfe des General Algebraic Modeling System (GAMS) gelöst wird..<br>
  Die Web-Applikation basiert auf dem <a href="http://3rd-edition.railstutorial.org/">Ruby on Rails Tutorial – Learn Web Development with Rails</a> von Michael Hartl.<br>
</p>
</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Kontakt") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | EvenTraum</title>
</head>
<body>
<h1>Kontakt</h1>
<p>Kontaktieren Sie bei Rückfragen oder Anregungen gerne das EvenTraum-Team.</p>
<br><br>
<%= mail_to ("xelat.akcam@gmail.com"), "Xelat Akcam", :style=> "font-weight: bold" %><br><br>
<div style="text-align:left"><%=image_tag("email.png", size: "25") + "  xelat.akcam@gmail.com" %></div>
<br><br>
<%= mail_to ("ha.boulakhrif@web.de"), "Hayat Boulakhrif", :style=> "font-weight: bold" %><br><br>
<div style="text-align:left"><%=image_tag("email.png", size: "25") + "  ha.boulakhrif@web.de" %></div>
<br><br>
<%= mail_to ("nadia.kruszewski@yahoo.de"), "Nadia Kruszewski", :style=> "font-weight: bold" %><br><br>
<div style="text-align:left"><%=image_tag("email.png", size: "25") + "  nadia.kruszewski@yahoo.de" %></div>

</body>
</html>


app/views/static_pages/home.html.erb
<% provide(:title, "Startseite") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | EvenTraum</title>
</head>
<ul class="bxslider">
  <div style="text-align:center"><%=image_tag("Image_0.png") %></div>
  <div style="text-align:center"><%=image_tag("Image_1.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_3.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_5.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_6.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_7.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_8.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_9.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_10.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_12.jpg") %></div>
</ul>
</html>

app/views/static_pages/impression.html.erb
<% provide(:title, "Impressionen") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | EvenTraum</title>
</head>
<body>
<h1>Impressionen</h1>
<% if logged_in? %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
        <section class="micropost_form">
          <%= render 'shared/micropost_form' %>
        </section>
      </aside>
    </div>
<% end %>

<div class="span8">
  <ul class="microposts">
    <li>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    </li>
  </ul>
</div>
</body>
</html>

app/views/static_pages/impressum.html.erb
<% provide(:title, "Impressum") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | EvenTraum</title>
</head>
<body>
<h1>Impressum</h1>
<h2>EvenTraum</h2>
<p>c/o Leibniz Universität Hannover<br>
  Institut für Produktionswirtschaft<br>
  Königsworther Platz 1<br>
  D-30167 Hannover<br><br>
  Vertretungsberichtsberechtigter Vorstand:<br>
  Xelat Akcam<br>
  Hayat Boulakhrif<br>
  Nadia Kruszewski</p><br>
<h2>Disclaimer (Haftungsausschluss)</h2>
<h2>1. Inhalt des Onlineangebotes</h2>
<p>Als Betreiber von Eventraum und inhaltlich Verantwortlicher dieser Website übernimmt die Eventraum GmbH, nachfolgend EVENTRAUM genannt, keinerlei Gewähr für Aktualität, Korrektheit, Vollständigkeit oder Qualität der bereitgestellten Informationen. Haftungsansprüche gegen das EVENTRAUM, welche sich auf Schäden materieller oder ideeller Art beziehen, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter und unvollständiger Informationen verursacht wurden, sind grundsätzlich ausgeschlossen, sofern seitens des EVENTRAUM kein nachweislich vorsätzliches oder grob fahrlässiges Verschulden vorliegt.
  Alle Angebote sind freibleibend und unverbindlich. Das EVENTRAUM behält es sich ausdrücklich vor, Teile der Seiten oder das gesamte Angebot ohne gesonderte Ankündigung zu verändern, zu ergänzen, zu löschen oder die Veröffentlichung zeitweise oder endgültig einzustellen.</p>
<h2>2. Verweise und Links</h2>
<p>Bei direkten oder indirekten Verweisen auf fremde Internetseiten ("Links"), die außerhalb des Verantwortungsbereiches des EVENTRAUMs liegen,
  besteht keine Haftungsverpflichtung. Das EVENTRAUM erklärt hiermit ausdrücklich,
  dass zum Zeitpunkt der Linksetzung keine illegalen oder moralisch verwerflichen Inhalte auf den zu verlinkenden Seiten erkennbar waren.
  Auf die aktuelle und zukünftige Gestaltung, die Inhalte oder die Urheberschaft der gelinkten/verknüpften Seiten hat das EVENTRAUM
  keinerlei Einfluss.
  Deshalb distanziert sich das EVENTRAUM hiermit ausdrücklich von allen Inhalten aller gelinkten/verknüpften Seiten,
  die nach der Linksetzung verändert wurden. Diese Feststellung gilt für alle innerhalb des eigenen Internetangebotes gesetzten Links
  und Verweise sowie für Fremdeinträge innerhalb des Gästebuchs. Für illegale, fehlerhafte oder unvollständige Inhalte und insbesondere
  für Schäden, die aus der Nutzung oder Nichtnutzung solcherart dargebotener Informationen entstehen, haftet allein der Anbieter der Seite,
  auf welche verwiesen wurde, nicht derjenige, der über Links auf die jeweilige Veröffentlichung lediglich verweist.</p>
<h2>3. Datenschutz</h2>
<p>Innerhalb des Internetangebotes besteht die Möglichkeit zur Eingabe persönlicher Daten (Emailadressen, Namen),
  wobei die Preisgabe dieser Daten seitens des Nutzers auf ausdrücklich freiwilliger Basis erfolgt.
  Der Nutzer erklärt sich automatisch zur Speicherung und Verarbeitung dieser Informationen bereit,
  welche vom EVENTRAUM nicht an Dritte weitergegeben und diskret behandelt werden.
  Das EVENTRAUM behält sich vor, persönliche Daten in anonymisierter oder statistischer Form zu veröffentlichen.</p>
<h2>4. Rechtswirksamkeit dieses Haftungsausschlusses</h2>
<p>Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten, von dem aus auf diese Seite verwiesen wurde. Sofern Teile oder einzelne Formulierungen dieses Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollständig entsprechen sollten, bleiben die übrigen Teile des Dokumentes in ihrem Inhalt und ihrer Gültigkeit davon unberührt.</p>
</body>
</html>

app/views/static_pages/offer.html.erb
<% provide(:title, "Angebot") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | EvenTraum</title>
</head>
<body>
<h1>EvenTraum realisiert das Event Ihrer Träume</h1>
<p>
  Die Planung eines Events ist meist mit viel Aufwand und Stress verbunden.
  Der Service von EvenTraum bietet Ihnen an, die gesamte Organisation Ihres Events zu übernehmen,
  so dass Sie sich ganz in Ruhe auf Ihre Veranstaltung freuen können.<br><br>
  Der EvenTraum-Rundum-Service bietet das gesamte Spektrum der Veranstaltungsorganisation, von der Konzeptentwicklung bis zur Durchführung.
  Durch unser breites Portfolio können Sie Events mit einer beliebigen Anzahl von Gästen planen lassen.
  Gerne stellen wir Ihnen auch nur Teile unseres Angebots zur Verfügung. Sie allein entscheiden, was zu Ihrem Traum-Event dazugehört.<br><br>
  Ob Catering, Entertainment oder die passende Raumdekoration – wir kümmern uns um all Ihre persönlichen Wünsche.
  Es ist uns ein Herzensanliegen, durch unser Rundum-Service der besonderen Art, ein perfektes Event für Sie zu planen.
  Unser Ziel besteht darin einzigartige und unvergessliche Erlebnismomente für Sie und Ihre Gäste zu erschaffen.
</p>
</body>
<body>
<div class="info">
  <div style==><%=image_tag("Image_8.jpg", width: "550", height:  "350") %></div>
  <p>
    Unser vielseitiges Portfolio an unterschiedlichsten Räumlichkeiten erlaubt es uns jegliche Art und Größe von Veranstaltungen zu organisieren.
    Von Familienfeiern und Hochzeiten über Betriebsfeiern bis hin zu Preisverleihungen – EvenTraum realisiert jedes Event.<br><br>
    Die Räume erfüllen höchste Ansprüche und sind je nach Geschmack und Anlass glanzvoll, gemütlich oder modern.
    Auf Wunsch können wir hoch innovative Rauminszenierungen, einen glanzvollen Außenbereich oder einen beeindruckenden Ausblick realisieren.
    Selbstverständlich sorgen wir auch für eine dem Anlass entsprechende Raumdekoration.<br><br>
    Teilen Sie uns Ihre Präferenzen gerne mit - EvenTraum findet die geeignete Location für Ihren Anlass.
  </p>
</div>
</body>
<br>
<body>
<div class="info">
  <div style=><%=image_tag("Image_3.jpg", width: "550", height: "350")%></div>
  <p>
    Gutes Essen verbreitet gute Laune – daher kommt die Bewirtung der Gäste mit Getränken und Speisen bei EvenTraum nicht zu kurz.
    Seien es Köstlichkeiten aus der deutschen, spanischen, griechischen, französischen, italienischen oder orientalischen Küche
    - aus unserem vielfältigen und internationalen Catering-Angebot können sie je nach Geschmack kombinieren.<br>
    Die Speisen können sowohl als Buffet als auch als Menü serviert werden.<br><br>
    Der Rundum-Service von EvenTraum sorgt für das Eindecken und Dekorieren der großen Tafel oder der Tischgruppen
    durch unser Catering-Personal, welches die Gäste bei Ihrer Veranstaltung schließlich auch bedient und deren besonderen Wünsche erfüllt.<br><br>
    Gerne kreiert unser Konditor eine schicke Torte zum Geburtstag, Hochzeitstag oder einem anderen Anlass.
  </p>
</div>
</body>
<body>
<div class="info">
  <div style=><%=image_tag("Image_10.jpg", width: "550", height: "350")%></div>
  <p>
    EvenTraum kümmert sich um die passende musikalische Untermalung Ihres Events - ob als kurze Einlage,
    im Hintergrund oder als abendfüllendes Programm.<br><br>
    Im Bereich der Live Musik bieten wir Ihnen attraktive Ensembles in verschiedenen Besetzungen aus allen Stilrichtungen:
    Von Klassik über Swing und Jazz bis hin zu Tanz- und Party-Musik. Auch andere Besetzungen oder ein DJ können der Veranstaltung
    den passenden musikalischen Rahmen verleihen.<br><br>
    Mit dem richtigen Ton wird Ihr Event perfekt abgerundet.
  </p>
</div>
</body>
<br><br><br><br><br><br><br><br>
<p>
  Erlauben Sie uns einen kleinen Einblick in Ihre Vorstellung bezüglich Ihres Events zu gewinnen und lassen Sie sich ganz sorgenfrei
  von uns überraschen.<br>
  Mit viel Engagement und Liebe bis ins kleinste Detail plant unser kreatives und zugleich kompetentes EvenTraum-Team Ihr nächstes Event.<br><br>
  Fordern Sie uns heraus – wir  freuen uns auf Sie!
</p>
</html>

app/views/static_pages/tcpsp.html.erb
<% if logged_in? %>
    <% if current_user.admin? && !current_user?(users_path) %>

        <% provide(:title, 'Eventplanung') %>
        <h1>Optimierung der Eventplanung</h1>

        <p>Hier gehts es zur Verwaltung ...</p><br>
        <div class="linkcontainer">
          <div class="centerwrapper">

            <div class="image">
              <%= link_to image_tag("Events.jpg", height: '80'), events_path %><br>
              <%= link_to "der Events!", events_path %>
            </div>

            <div class="image">
              <%= link_to image_tag("Vorgänge.png", height: '80'), jobs_path %><br>
              <%= link_to "der Vorgänge!", jobs_path %>
            </div>

            <div class="image">
              <%= link_to image_tag("Event-Vorgänger-Nachfolger_Beziehungen.png", height: '80'), event_job_job_associations_path %><br>
              <%= link_to "der Vorgänger-Nachfolger-Beziehungen der Events!", event_job_job_associations_path %>
            </div>
          </div>
        </div>
        <br><br><br><br><br><br><br><br><br>
        <div class="linkcontainer">
          <div class="centerwrapper">
            <div class="image">
              <%= link_to image_tag("Event-Vorgänger-Periode.jpg", height: '80'), event_job_period_associations_path %><br>
              <%= link_to "der Event-Vorgangs-Endzeitpunkte!", event_job_period_associations_path %>
            </div>

            <div class="image">
              <%= link_to image_tag("Perioden&Zusatzkapazitäten.png", height: '80'), periods_path %><br>
              <%= link_to "der Perioden und zur Anzeige der Zusatzkapazitäten!", periods_path %>
            </div>

            <div class="image">
              <%= link_to image_tag("gams.jpg", height: '80'), gams_paths_path %><br>
              <%= link_to 'des GAMS-Pfads!', gams_paths_path %>
            </div>
          </div>
        </div>
        <br><br><br><br><br><br><br><br><br><br><br>

        <%= button_to "Ergebnisse entfernen", {:controller => 'event_job_period_associations', :action => 'delete_old_plan'},{:class => "btn btn-primary"} %>
        <br><div style="text-align:center"><%=image_tag("pfeil.png", size: "50")%></div><br>
        <%= button_to "Eventplanung optimieren", {:controller => 'event_job_period_associations', :action => 'optimize'},{:class => "btn btn-primary"} %>
        <br><div style="text-align:center"><%=image_tag("pfeil.png", size: "50")%></div><br>
        <%= button_to "Ergebnisse einlesen", {:controller => 'event_job_period_associations', :action => 'read_optimization_results'},{:class => "btn btn-primary"} %>

        <% if @objective_function_value!=nil %>
            Die Kosten betragen <%=   @objective_function_value %> Geldeinheiten!<br><br>
        <% end %>
    <% end %>
<% end %>