config/routes.rb
Rails.application.routes.draw do

  resources :gams_paths
  resources :event_job_job_associations
  resources :event_job_period_associations
  resources :periods
  resources :jobs
  resources :events
  resources :users
  resources :microposts,          only: [:create, :destroy]

  root 'static_pages#home'

  get 'sessions/new'
  get 'users/new'
  get 'signup'     => 'users#new'
  get 'login'      => 'sessions#new'
  get 'home'        => 'static_pages#home'
  get 'impression' => 'static_pages#impression'
  get 'offer'      => 'static_pages#offer'
  get 'tcpsp'      => 'static_pages#tcpsp'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'impressum'    => 'static_pages#impressum'

  post 'event_job_periods/delete_old_plan', :to => 'event_job_period_associations#delete_old_plan'
  post 'event_job_periods/optimize', :to => 'event_job_period_associations#optimize'
  post 'event_job_periods/read_optimization_results', :to => 'event_job_period_associations#read_optimization_results'
  post "periods/change", as: :change_periods
  post   'login'   => 'sessions#create'
  post   'logout'   => 'sessions#destroy'

  delete 'logout'  => 'sessions#destroy'

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :event
  has_many :periods, through: :event_job_period_associations
  has_many :event_job_job_associations, foreign_key: "successor_id", :dependent => :destroy
  has_many :event_reverse_job_associations, foreign_key: "predecessor_id", class_name: "EventJobJobAssociation", :dependent => :destroy
  has_many :successors, through: :event_job_job_associations, source: :successor_id
  has_many :predecessors, through: :event_reverse_job_associations, source: :predecessor_id
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)


    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Der Vorgang wurde erfolgreich angelegt.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Der Vorgang wurde erfolgreich aktuaisiert.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Der Vorgang wurde entfernt.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def job_params
    params.require(:job).permit(:event_id, :name, :jobtext, :processing_time, :ressource_demand)
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<% if logged_in? %>
    <% if current_user.admin? && !current_user?(users_path) %>
        <%= form_for(@job) do |f| %>
            <% if @job.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

                  <ul>
                    <% @job.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <div class="field">
              <%= f.label 'Event auswählen' %><br>
              <%= f.collection_select :event_id, Event.all, :id, :name%>
            </div>
            <div class="field">
              <%= f.label 'Vorgang' %><br>
              <%= f.text_field :name%>
            </div>
            <div class="field">
              <%= f.label :jobtext, 'Beschreibung des Vorgangs' %><br>
              <%= f.text_area :jobtext%>
            </div>
            <div class="field">
              <%= f.label :processing_time, 'Dauer des Vorgangs' %><br>
              <%= f.text_field :processing_time, type: "number", min:0, required: "required" %>
            </div>
            <div class="field">
              <%= f.label :ressource_demand, 'Ressourcenbedarf des Vorgangs' %><br>
              <%= f.number_field :ressource_demand, type: "number", min:0, required: "required" %>
            </div>
            <div class="actions">
              <%= f.submit 'Neuen Vorgang anlegen oder aktualisieren', {:class => "btn btn-primary"} %>
            </div>
        <% end %>
    <% end %>
<% end %>

app/views/jobs/edit.html.erb
<% if logged_in? %>
    <% if current_user.admin? && !current_user?(users_path) %>
        <% provide(:title, "Verwaltung") %>

        <h1>Aktualisierung der Vorgänge</h1>

        <%= render 'form' %>

        <%= link_to 'Anzeigen', @job %> |
        <%= link_to 'Zurück', jobs_path %>
    <% end %>
<% end %>

app/views/jobs/index.html.erb
<% if logged_in? %>
    <% if current_user.admin? && !current_user?(users_path) %>
        <% provide(:title, "Verwaltung") %>

        <h1>Übersicht der Vorgänge</h1>

        <div style="width: auto">
          <table id="events" class="table table-striped table-bordered">
            <thead>
            <tr>
              <th>Event</th>
              <th>Vorgang</th>
              <th>Beschreibung</th>
              <th width="100">Dauer des Vorgangs</th>
              <th width="150">Ressourcenbedarf des Vorgangs</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
            </thead>

            <tbody>
            <% @jobs.each do |job| %>
                <tr>
                  <td><%= job.event.name %></td>
                  <td><%= job.name %></td>
                  <td><%= job.jobtext %></td>
                  <td><%= job.processing_time %></td>
                  <td><%= job.ressource_demand %></td>
                  <td><%= link_to 'Anzeigen', job %></td>
                  <td><%= link_to 'Ändern', edit_job_path(job) %></td>
                  <td><%= link_to 'Entfernen', job, method: :delete, data: { confirm: 'Möchten Sie diesen Eintrag sicher entfernen?' } %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
          <br>
          <%= button_to 'Neuen Vorgang anlegen', new_job_path, method: :get, :class => "btn btn-primary" %>
          <br>
          <%= link_to 'Zurück zur Eventplanung', tcpsp_path %>
        </div>
    <%end%>
<%end%>

app/views/jobs/new.html.erb
<% if logged_in? %>
    <% if current_user.admin? && !current_user?(users_path) %>
        <% provide(:title, "Verwaltung") %>

        <h1>Neuer Vorgang</h1>

        <%= render 'form' %>

        <%= link_to 'Zurück', jobs_path %>
    <% end %>
<% end %>

app/views/jobs/show.html.erb
<% if logged_in? %>
    <% if current_user.admin? && !current_user?(users_path) %>
        <% provide(:title, "Verwaltung") %>

        <p id="notice"><%= notice %></p>

        <p>
          <strong>Event:</strong>
          <%= @job.event.name %>
        </p>

        <p>
          <strong>Vorgang:</strong>
          <%= @job.name %>
        </p>

        <p>
          <strong>Beschreibung:</strong>
          <%= @job.jobtext %>
        </p>

        <p>
          <strong>Vorgangsdauer:</strong>
          <%= @job.processing_time %>
        </p>

        <p>
          <strong>Ressourcenbedarf:</strong>
          <%= @job.ressource_demand %>
        </p>

        <%= link_to 'Ändern', edit_job_path(@job) %> |
        <%= link_to 'Zurück', jobs_path %>
    <% end %>
<% end %>