config/routes.rb
Rails.application.routes.draw do

  resources :gams_paths
  resources :event_job_job_associations
  resources :event_job_period_associations
  resources :periods
  resources :jobs
  resources :events
  resources :users
  resources :microposts,          only: [:create, :destroy]

  root 'static_pages#home'

  get 'sessions/new'
  get 'users/new'
  get 'signup'     => 'users#new'
  get 'login'      => 'sessions#new'
  get 'home'        => 'static_pages#home'
  get 'impression' => 'static_pages#impression'
  get 'offer'      => 'static_pages#offer'
  get 'tcpsp'      => 'static_pages#tcpsp'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'impressum'    => 'static_pages#impressum'

  post 'event_job_periods/delete_old_plan', :to => 'event_job_period_associations#delete_old_plan'
  post 'event_job_periods/optimize', :to => 'event_job_period_associations#optimize'
  post 'event_job_periods/read_optimization_results', :to => 'event_job_period_associations#read_optimization_results'
  post "periods/change", as: :change_periods
  post   'login'   => 'sessions#create'
  post   'logout'   => 'sessions#destroy'

  delete 'logout'  => 'sessions#destroy'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :jobs, dependent: :destroy
  has_many :periods, through: :event_job_period_associations
  has_many :event_job_period_associations, dependent: :destroy
  has_many :event_job_job_associations, dependent: :destroy
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Das Event wurde erfolgreich aktualisiert.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Das Event wurde entfernt.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :eventtext, :guest, :deadline)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% if logged_in? %>
    <%= form_for(@event) do |f| %>
        <% if @event.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

              <ul>
                <% @event.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label 'Anlass' %><br>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :eventtext, "Hier ist Raum für Ihre Träume bezüglich Ihres Events:" %><br>
          <%= f.text_area :eventtext%>
        </div>
        <div class="field">
          <%= f.label :guest, 'Anzahl der Gäste' %><br>
          <%= f.number_field :guest,type: "number", min:0%>
        </div>
        <div class="field">
          <%= f.label :deadline, 'Datum des Events' %><br>
          <%= f.date_select :deadline, prompt: { day: 'Tag', month: 'Monat', year: 'Jahr' }, start_year:2017 %>
        </div>

        <div class="actions">
          <%= f.submit 'Event anlegen oder aktualisieren', {:class => "btn btn-primary"} %>
        </div>
    <% end %>
<% end %>

app/views/events/edit.html.erb
<% provide(:title, "Verwaltung") %>

<h1>Aktualisierung des Events</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @event %> |
<%= link_to 'Zurück', events_path %>

app/views/events/index.html.erb
<% provide(:title, "Verwaltung") %>
<% if logged_in? %>
    <% if current_user.admin? && !current_user?(users_path) %>

        <h1>Übersicht der Events</h1>

        <div style="width: auto">
          <table id="events" class="table table-striped table-bordered">
            <thead>
            <tr>
              <th>Anlass</th>
              <th>Persönliche Wünsche</th>
              <th>Anzahl der Gäste</th>
              <th>Datum des Events</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% @events.each do |event| %>
                <tr>
                  <td><%= event.name %></td>
                  <td><%= event.eventtext %></td>
                  <td><%= event.guest %></td>
                  <td><%= event.deadline %></td>
                  <td><%= link_to 'Anzeigen', event %></td>
                  <td><%= link_to 'Ändern', edit_event_path(event) %></td>
                  <td><%= link_to 'Entfernen', event, method: :delete, data: { confirm: 'Möchten Sie diesen Eintrag sicher entfernen?' } %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
          <br>
          <%= button_to 'Neues Event anlegen', new_event_path, method: :get, :class => "btn btn-primary" %>
          <br><br>
          <%= link_to 'Zurück zur Eventplanung', tcpsp_path %>

    <% else %>

        <h1>Mein neues Event</h1>
        <p>Wir freuen uns, dass Sie sich dazu entschieden haben, Ihr nächstes Event von unserem EvenTraum-Team realisieren zu lassen.<br>
          Bitte teilen Sie uns nachfolgend Ihre genauen Vorstellungen und Anforderungen mit, damit wir einen Einblick in Ihren Traum gewinnen können.</p><br>
        <%= button_to "Event in Auftrag geben" , new_event_path, method: :get, :class => "btn btn-primary" %>

    <% end %>
<% end %>
</div>

app/views/events/new.html.erb
<% provide(:title, "Verwaltung") %>
<% if logged_in? %>

    <h1>Neues Event</h1>

    <%= render 'form' %>

    <%= link_to 'Zurück', events_path %>
<% end %>

app/views/events/show.html.erb
<% provide(:title, "Verwaltung") %>

<% if logged_in? %>

    <div class="alert alert-success fade in">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      <strong>Herzlichen Dank!</strong> Ihr Auftrag wurde erfolgreich erstellt. Sie haben eine Bestätigungsemail erhalten. In Kürze werden wir Sie kontaktieren.
    </div>

    <p>
      <strong>Anlass:</strong>
      <%= @event.name %>
    </p>

    <p>
      <strong>Persönliche Wünsche:</strong>
      <%= @event.eventtext %>
    </p>

    <p>
      <strong>Anzahl der Gäste:</strong>
      <%= @event.guest %>
    </p>

    <p>
      <strong>Datum des Events:</strong>
      <%= @event.deadline %>
    </p>


    <%= link_to 'Ändern', edit_event_path(@event) %> |
    <%= link_to 'Zurück', events_path %>
<% end %>