config/routes.rb
Rails.application.routes.draw do

  resources :gams_paths
  resources :event_job_job_associations
  resources :event_job_period_associations
  resources :periods
  resources :jobs
  resources :events
  resources :users
  resources :microposts,          only: [:create, :destroy]

  root 'static_pages#home'

  get 'sessions/new'
  get 'users/new'
  get 'signup'     => 'users#new'
  get 'login'      => 'sessions#new'
  get 'home'        => 'static_pages#home'
  get 'impression' => 'static_pages#impression'
  get 'offer'      => 'static_pages#offer'
  get 'tcpsp'      => 'static_pages#tcpsp'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'impressum'    => 'static_pages#impressum'

  post 'event_job_periods/delete_old_plan', :to => 'event_job_period_associations#delete_old_plan'
  post 'event_job_periods/optimize', :to => 'event_job_period_associations#optimize'
  post 'event_job_periods/read_optimization_results', :to => 'event_job_period_associations#read_optimization_results'
  post "periods/change", as: :change_periods
  post   'login'   => 'sessions#create'
  post   'logout'   => 'sessions#destroy'

  delete 'logout'  => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>Copyright © EvenTraum 2017</p>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Über uns", about_path %></li>
      <li><%= link_to "Kontakt", contact_path %></li>
      <li><%= link_to "Impressum", impressum_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "EvenTraum", root_path %></li>
        <li><%= link_to "Impressionen", impression_path %></li>

        <% if logged_in? %>

            <% if current_user.admin? && !current_user?(users_path) %>
                <li><%= link_to "Nutzer", users_path %></li>
                <li><%= link_to "Eventplanung", tcpsp_path %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Mein Konto <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profil", current_user %></li>
                    <li><%= link_to "Einstellungen", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Abmelden", logout_path, method: "destroy" %>
                    </li>
                  </ul>
                </li>

            <% else %>

                <li><%= link_to "Mein Event", events_path %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Mein Konto <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profil", current_user %></li>
                    <li><%= link_to "Einstellungen", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Abmelden", logout_path, method: "destroy" %>
                    </li>
                  </ul>
                </li>
            <% end %>

        <% else %>

            <li><%= link_to "Angebot", offer_path %></li>
            <li><%= link_to "Anmelden", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>